[project]
name = "mcp-office-word"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "docx2pdf>=0.1.8",
    "mcp[cli]>=1.9.0",
    "msoffcrypto-tool>=5.4.2",
    "python-docx>=1.1.2",
]
